# Generated by Django 3.2.5 on 2021-09-01 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0002_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='the_wall.users'),
        ),
    ]
